language: c
sudo: false
before_install:
  - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)
install:
  - ln -s $PWD/ninSpectrumDisplay /home/travis/arduino_ide/libraries/ninSpectrumDisplay
  - arduino --install-library "Adafruit NeoPixel"
script:
  - build_main_platforms
notifications:
  email:
    on_success: change
    on_failure: change